services:
  - type: web
    name: openclaw
    runtime: image
    image:
      url: ghcr.io/heetisk/openclaw:latest

    plan: free
    
    healthCheckPath: /healthz
    envVars:
      - key: OPENCLAW_STATE_DIR
        value: /tmp/.openclaw
      - key: OPENCLAW_WORKSPACE_DIR
        value: /tmp/workspace
      - key: OPENCLAW_GATEWAY_TOKEN
        generateValue: true
